version: '3.8'

services:
  api-gateway-service: # Renamed api-gateway to api-gateway-service
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    container_name: api-gateway-service # Updated container name
    restart: always
    env_file:
      - .env
    ports:
      - '4199:4199'
    depends_on:
      - rabbitmq-hr
  user-service:
    build:
      context: .
      dockerfile: ./apps/user-service/Dockerfile
      target: development
    command: yarn start:dev user-service
    restart: always
    env_file:
      - .env
    depends_on:
      - user-db-service
      - rabbitmq-hr
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4004:4004'

  hr:
    build:
      context: .
      dockerfile: ./apps/hr/Dockerfile
      target: development
    command: yarn start:dev hr
    restart: always
    env_file:
      - .env
    depends_on:
      - hr-db
      - rabbitmq-hr
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4003:4003'

  rabbitmq-hr:
    image: rabbitmq:management
    container_name: rabbitmq-hr # Updated container name to avoid conflict
    restart: always
    ports:
      - '5672:5672' # Fix to default RabbitMQ port
      - '15672:15672' # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_NODE_PORT=5672

  user-db-service: # Renamed user-db to user-db-service
    container_name: user-db-service # Updated container name
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user-db
      - PGPORT=5436
    volumes:
      - user-hr-db-data:/var/lib/postgresql/data
    ports:
      - '5436:5436'

  hr-db:
    container_name: hr-db
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hr-db
      - PGPORT=5435
    volumes:
      - hr-db-data:/var/lib/postgresql/data
    ports:
      - '5435:5435'

volumes:
  user-hr-db-data:
  hr-db-data:
