name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest -f ./apps/api-gateway/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hr:latest -f ./apps/hr/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/hr:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/payroll/balanzify-hr-payroll
            git pull origin main
            docker-compose pull
            docker-compose up -d --build
            docker system prune -af
